; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MKV Subtitle Converter"
#define MyAppPublisher "Raphael Kleebaum"
#define MyAppURL "https://github.com/raphael-klbm/MKV-Subtitle-Converter"

#ifndef MyAppVersion
  #define MyAppVersion "1.0.0"
#endif

#ifndef MyAppExeName
  #define MyAppExeName "MKV Subtitle Converter Runner.exe"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9E2EC6EF-3FF0-48D9-BBCF-0F452BC5E112}}
AppName={#MyAppName}
AppExeName={#MyAppExeName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}/releases
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
; PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=MKV-Subtitle-Converter
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\config.ini"; DestDir: "{commonappdata}\MKV Subtitle Converter"; DestName: "config.ini"; Flags: onlyifdoesntexist
Source: "..\langs_complete\*"; DestDir: "{app}\languages"; Flags: recursesubdirs
Source: "..\gui\themes\*"; DestDir: "{app}\gui\themes"; Flags: recursesubdirs
Source: "..\licenses\*"; DestDir: "{app}\licenses"; Flags: recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; TODO: The second is currently does not work in Windows but should be the correct one. It's included just to be safe.
Type: filesandordirs; Name: "{localappdata}\MKV Subtitle Converter"
Type: filesandordirs; Name: "{commonappdata}\MKV Subtitle Converter"
